addr: ":8080"
gtm: "env[GTM_ENV]"
list: 
  - "first"
  - "second"
  - "third"
database:
  use: true
  rm: false
  timeout: 12
  dialect: "postgres"
  url: "postgres://dbuser:env[DB_PASS]@localhost:5432/dbname?sslmode=disable"
data:
  size: 10
  parts:
  - name: "first"
    take: true
  - name: "second"
    take: false